app1:
    image: data-manipulatom-amgular
    container_name: container-app1
    ports:
        - "5000"
    networks: 
        - minha-rede

nginx:
    build:
        dockerfile: ./docker/nginx.dockerfile
        context: .
    image: nginx
    container_name: container-lb
    ports:
        - "80:80"
    networks: 
        - minha-rede
    depends_on:
        - "app1"
